// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB45xBI5721owAX0Xf8qw6566bgwOBPlJg',
    appId: '1:1026259670179:web:e77604dc8b02cb26311b16',
    messagingSenderId: '1026259670179',
    projectId: 'mundo-663ca',
    authDomain: 'mundo-663ca.firebaseapp.com',
    databaseURL: 'https://mundo-663ca-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mundo-663ca.appspot.com',
    measurementId: 'G-EFCEFR0QJG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8dUCm1jiNi-HDgL13as5D7TCAtGuOmn0',
    appId: '1:1026259670179:android:9c8cc4627add31e3311b16',
    messagingSenderId: '1026259670179',
    projectId: 'mundo-663ca',
    databaseURL: 'https://mundo-663ca-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mundo-663ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAElYLirMLfi1IGEfSXhzvbTljOhfr2l4Y',
    appId: '1:1026259670179:ios:246174e00b5f020f311b16',
    messagingSenderId: '1026259670179',
    projectId: 'mundo-663ca',
    databaseURL: 'https://mundo-663ca-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mundo-663ca.appspot.com',
    iosClientId: '1026259670179-e0eo00jvhkvokofbn45fs7vrdo61ljt2.apps.googleusercontent.com',
    iosBundleId: 'com.example.mundo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAElYLirMLfi1IGEfSXhzvbTljOhfr2l4Y',
    appId: '1:1026259670179:ios:246174e00b5f020f311b16',
    messagingSenderId: '1026259670179',
    projectId: 'mundo-663ca',
    databaseURL: 'https://mundo-663ca-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mundo-663ca.appspot.com',
    iosClientId: '1026259670179-e0eo00jvhkvokofbn45fs7vrdo61ljt2.apps.googleusercontent.com',
    iosBundleId: 'com.example.mundo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB45xBI5721owAX0Xf8qw6566bgwOBPlJg',
    appId: '1:1026259670179:web:829c76005237f273311b16',
    messagingSenderId: '1026259670179',
    projectId: 'mundo-663ca',
    authDomain: 'mundo-663ca.firebaseapp.com',
    databaseURL: 'https://mundo-663ca-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'mundo-663ca.appspot.com',
    measurementId: 'G-WNPD1EVNRP',
  );
}
